### ISSUE TITLE
Output not correctly rendered for code

### ISSUE THREAD

**Issue by menardorama** [RocketChat/Rocket.Chat.OpenAI.Completions.App#4]
Hi,

Tanks a lot for this extension, chatting with ChatGPT is working great.
I see one issue on my side is that when you request some example of code, the result is not formatted as a code block.

This result in a wrongly displayed code and need to be manually re ident

It would be great if code block could be correctly displayed as it is on ChatGPT.

Maybe the answer can be for now displayed in a code block to be sure that there is no formatting ?

Thanks

**Comment by menardorama** [comment]
quick precision, it works for powershell scripts but not on bash or python script...
'#' seems to be an issue for me

**Comment by dudanogueira** [comment]
Hi @menardorama Thanks for the input!

It's fixed now :)
