### ISSUE TITLE
Unable to ignore/mute ChatGPT 

### ISSUE THREAD

**Issue by jbd** [RocketChat/Rocket.Chat.OpenAI.Completions.App#5]
Hello,

when I try to ignore/mute ChatGPT in a discussion, I've got a 'Invalid subscription or 'User not in this room' error.  Maybe it's related to Rocket.Chat and not this application ?

Thank you.

**Comment by dudanogueira** [comment]
Hi! Thanks for this input!

That's right. And not sure if this is a bug itself.

The ignore/mute options is on a per room basis.
